image: node:16-alpine

stages:
  - prepare
  - test
  - build
  - e2e_tests

variables:
  # ONE-wallet project on Bitrise
  BITRISE_PROJECT_SLUG: 6ee8c26f-6d7b-4bcb-8ddc-be1ba3cd2687

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

.only_main_or_manual:
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: on_success
    - when: manual

.bitrise_e2e:
  stage: e2e_tests
  image: registry.gitlab.procivis.ch/procivis/one/one-operations/bitrise-builder:0.1.0
  needs: [test]
  script:
    - >
      /etc/gitrise.sh
      --access-token $BITRISE_API_ACCESS_TOKEN
      --slug $BITRISE_PROJECT_SLUG
      --workflow $BITRISE_WORKFLOW
      --branch "$CI_COMMIT_REF_NAME"
      --env "CI_PIPELINE_ID:$CI_PIPELINE_ID"
      --output "artifacts"
  artifacts:
    paths:
      - artifacts
    expire_in: 10 days

.bitrise_build:
  stage: build
  image: registry.gitlab.procivis.ch/procivis/one/one-operations/bitrise-builder:0.1.0
  needs: [test]
  script:
    - >
      /etc/gitrise.sh
      --access-token $BITRISE_API_ACCESS_TOKEN
      --slug $BITRISE_PROJECT_SLUG
      --workflow $BITRISE_WORKFLOW
      --branch "$CI_COMMIT_REF_NAME"
      --env "CI_PIPELINE_ID:$CI_PIPELINE_ID"

.install-node-modules: &install-node-modules
  - >
    if [ -d ./node_modules ] && [ "$(ls -A ./node_modules)" ]; then
      echo "node_modules exists and seems valid, not re-installing deps."
    else
      echo "node_modules does not exist or is not valid, re-installing deps."
      apk add --update --no-cache --virtual .build-deps alpine-sdk libc6-compat gcompat
      yarn global add node-gyp @mapbox/node-pre-gyp --network-concurrency 1
      yarn install --frozen-lockfile --network-concurrency 1
      yarn rnuc:dev
    fi

.modules_setup:
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules/
    policy: pull
  before_script:
    - *install-node-modules

# CODE CHECKS
build_deps:
  stage: prepare
  extends: .modules_setup
  script:
    - ''
  cache:
    policy: pull-push

lint:
  stage: test
  needs: [build_deps]
  extends: .modules_setup
  script:
    - yarn lint

compile:
  stage: test
  needs: [build_deps]
  extends: .modules_setup
  script:
    - yarn compile

test:
  stage: test
  needs: [build_deps]
  extends: .modules_setup
  script:
    - yarn test --coverage
  artifacts:
    paths:
      - coverage/*
    expire_in: 3 days

sonarqube-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  dependencies: [test]
  needs: [test]
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar' # Defines the location of the analysis task cache
    GIT_DEPTH: '0' # Tells git to fetch all the branches of the project, required by the analysis task
  script:
    - sonar-scanner
  allow_failure: true
  extends:
    - .modules_setup
    - .only_main_or_manual
  before_script: [] # disable node_module fetching, yarn not available in the image

# APP BUILDs
build:
  parallel:
    matrix:
      - BITRISE_WORKFLOW:
          - Android_DEV
          - iOS_DEV
          - Android_TEST
          - iOS_TEST
          - Android_DEMO
          - iOS_DEMO
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && ($BITRISE_WORKFLOW == 'Android_DEV' || $BITRISE_WORKFLOW == 'iOS_DEV')
      when: on_success
    - if: $CI_COMMIT_BRANCH != 'main' && $BITRISE_WORKFLOW != 'Android_DEV' && $BITRISE_WORKFLOW != 'iOS_DEV'
      when: never
    - when: manual
  extends:
    - .bitrise_build

# E2E
e2e:
  parallel:
    matrix:
      - BITRISE_WORKFLOW:
          - E2E_iOS
          - E2E_Android
  extends:
    - .bitrise_e2e
    - .only_main_or_manual
